name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app .

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy kondo-back \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app \
          --platform managed \
          --region us-east1 \
          --allow-unauthenticated