name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Save service account key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-service-key.json

      - name: Authenticate Docker with gcloud
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > $HOME/gcloud-service-key.json
          gcloud auth activate-service-account --key-file="$HOME/gcloud-service-key.json"
          gcloud auth configure-docker
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-service .

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-service

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-service --platform managed --region us-central1 --allow-unauthenticated

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}